/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherPortalRouteImport } from './routes/teacher-portal'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StaffPortalRouteImport } from './routes/staff-portal'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherPortalIndexRouteImport } from './routes/teacher-portal.index'
import { Route as StaffPortalIndexRouteImport } from './routes/staff-portal.index'
import { Route as TeacherPortalStudentsRouteImport } from './routes/teacher-portal.students'
import { Route as TeacherPortalRegularizationRouteImport } from './routes/teacher-portal.regularization'
import { Route as TeacherPortalPupaRouteImport } from './routes/teacher-portal.pupa'
import { Route as TeacherPortalProfileRouteImport } from './routes/teacher-portal.profile'
import { Route as TeacherPortalPlannerRouteImport } from './routes/teacher-portal.planner'
import { Route as TeacherPortalNoticesRouteImport } from './routes/teacher-portal.notices'
import { Route as TeacherPortalMyAttendanceRouteImport } from './routes/teacher-portal.my-attendance'
import { Route as TeacherPortalHomeworkRouteImport } from './routes/teacher-portal.homework'
import { Route as TeacherPortalClassesRouteImport } from './routes/teacher-portal.classes'
import { Route as TeacherPortalCalendarRouteImport } from './routes/teacher-portal.calendar'
import { Route as TeacherPortalAttendanceRouteImport } from './routes/teacher-portal.attendance'
import { Route as StaffPortalTeachersRouteImport } from './routes/staff-portal.teachers'
import { Route as StaffPortalTeacherAttendanceRouteImport } from './routes/staff-portal.teacher-attendance'
import { Route as StaffPortalStudentsRouteImport } from './routes/staff-portal.students'
import { Route as StaffPortalRegularizationRouteImport } from './routes/staff-portal.regularization'
import { Route as StaffPortalProfileRouteImport } from './routes/staff-portal.profile'
import { Route as StaffPortalNoticesRouteImport } from './routes/staff-portal.notices'
import { Route as StaffPortalHomeworkRouteImport } from './routes/staff-portal.homework'
import { Route as StaffPortalClassesRouteImport } from './routes/staff-portal.classes'
import { Route as StaffPortalAttendanceRouteImport } from './routes/staff-portal.attendance'
import { Route as PortalSettingsRouteImport } from './routes/_portal.settings'
import { Route as PortalReportCardsRouteImport } from './routes/_portal.report-cards'
import { Route as PortalProfileRouteImport } from './routes/_portal.profile'
import { Route as PortalNoticeboardRouteImport } from './routes/_portal.noticeboard'
import { Route as PortalHomeworkRouteImport } from './routes/_portal.homework'
import { Route as PortalGalleryRouteImport } from './routes/_portal.gallery'
import { Route as PortalFeesRouteImport } from './routes/_portal.fees'
import { Route as PortalDocumentsRouteImport } from './routes/_portal.documents'
import { Route as PortalDiaryRouteImport } from './routes/_portal.diary'
import { Route as PortalDashboardRouteImport } from './routes/_portal.dashboard'
import { Route as PortalCalendarRouteImport } from './routes/_portal.calendar'
import { Route as PortalCafeteriaRouteImport } from './routes/_portal.cafeteria'
import { Route as PortalBusRouteImport } from './routes/_portal.bus'
import { Route as PortalAttendanceRouteImport } from './routes/_portal.attendance'
import { Route as PortalAcademicsRouteImport } from './routes/_portal.academics'

const TeacherPortalRoute = TeacherPortalRouteImport.update({
  id: '/teacher-portal',
  path: '/teacher-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPortalRoute = StaffPortalRouteImport.update({
  id: '/staff-portal',
  path: '/staff-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPortalIndexRoute = TeacherPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherPortalRoute,
} as any)
const StaffPortalIndexRoute = StaffPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffPortalRoute,
} as any)
const TeacherPortalStudentsRoute = TeacherPortalStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherPortalRoute,
} as any)
const TeacherPortalRegularizationRoute =
  TeacherPortalRegularizationRouteImport.update({
    id: '/regularization',
    path: '/regularization',
    getParentRoute: () => TeacherPortalRoute,
  } as any)
const TeacherPortalPupaRoute = TeacherPortalPupaRouteImport.update({
  id: '/pupa',
  path: '/pupa',
  getParentRoute: () => TeacherPortalRoute,
} as any)
const TeacherPortalProfileRoute = TeacherPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherPortalRoute,
} as any)
const TeacherPortalPlannerRoute = TeacherPortalPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => TeacherPortalRoute,
} as any)
const TeacherPortalNoticesRoute = TeacherPortalNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => TeacherPortalRoute,
} as any)
const TeacherPortalMyAttendanceRoute =
  TeacherPortalMyAttendanceRouteImport.update({
    id: '/my-attendance',
    path: '/my-attendance',
    getParentRoute: () => TeacherPortalRoute,
  } as any)
const TeacherPortalHomeworkRoute = TeacherPortalHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => TeacherPortalRoute,
} as any)
const TeacherPortalClassesRoute = TeacherPortalClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherPortalRoute,
} as any)
const TeacherPortalCalendarRoute = TeacherPortalCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TeacherPortalRoute,
} as any)
const TeacherPortalAttendanceRoute = TeacherPortalAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherPortalRoute,
} as any)
const StaffPortalTeachersRoute = StaffPortalTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => StaffPortalRoute,
} as any)
const StaffPortalTeacherAttendanceRoute =
  StaffPortalTeacherAttendanceRouteImport.update({
    id: '/teacher-attendance',
    path: '/teacher-attendance',
    getParentRoute: () => StaffPortalRoute,
  } as any)
const StaffPortalStudentsRoute = StaffPortalStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => StaffPortalRoute,
} as any)
const StaffPortalRegularizationRoute =
  StaffPortalRegularizationRouteImport.update({
    id: '/regularization',
    path: '/regularization',
    getParentRoute: () => StaffPortalRoute,
  } as any)
const StaffPortalProfileRoute = StaffPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffPortalRoute,
} as any)
const StaffPortalNoticesRoute = StaffPortalNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => StaffPortalRoute,
} as any)
const StaffPortalHomeworkRoute = StaffPortalHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => StaffPortalRoute,
} as any)
const StaffPortalClassesRoute = StaffPortalClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => StaffPortalRoute,
} as any)
const StaffPortalAttendanceRoute = StaffPortalAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StaffPortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReportCardsRoute = PortalReportCardsRouteImport.update({
  id: '/report-cards',
  path: '/report-cards',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNoticeboardRoute = PortalNoticeboardRouteImport.update({
  id: '/noticeboard',
  path: '/noticeboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHomeworkRoute = PortalHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => PortalRoute,
} as any)
const PortalGalleryRoute = PortalGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFeesRoute = PortalFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDiaryRoute = PortalDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCalendarRoute = PortalCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCafeteriaRoute = PortalCafeteriaRouteImport.update({
  id: '/cafeteria',
  path: '/cafeteria',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBusRoute = PortalBusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAttendanceRoute = PortalAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAcademicsRoute = PortalAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRoute
  '/staff-portal': typeof StaffPortalRouteWithChildren
  '/teacher': typeof TeacherRoute
  '/teacher-portal': typeof TeacherPortalRouteWithChildren
  '/academics': typeof PortalAcademicsRoute
  '/attendance': typeof PortalAttendanceRoute
  '/bus': typeof PortalBusRoute
  '/cafeteria': typeof PortalCafeteriaRoute
  '/calendar': typeof PortalCalendarRoute
  '/dashboard': typeof PortalDashboardRoute
  '/diary': typeof PortalDiaryRoute
  '/documents': typeof PortalDocumentsRoute
  '/fees': typeof PortalFeesRoute
  '/gallery': typeof PortalGalleryRoute
  '/homework': typeof PortalHomeworkRoute
  '/noticeboard': typeof PortalNoticeboardRoute
  '/profile': typeof PortalProfileRoute
  '/report-cards': typeof PortalReportCardsRoute
  '/settings': typeof PortalSettingsRoute
  '/staff-portal/attendance': typeof StaffPortalAttendanceRoute
  '/staff-portal/classes': typeof StaffPortalClassesRoute
  '/staff-portal/homework': typeof StaffPortalHomeworkRoute
  '/staff-portal/notices': typeof StaffPortalNoticesRoute
  '/staff-portal/profile': typeof StaffPortalProfileRoute
  '/staff-portal/regularization': typeof StaffPortalRegularizationRoute
  '/staff-portal/students': typeof StaffPortalStudentsRoute
  '/staff-portal/teacher-attendance': typeof StaffPortalTeacherAttendanceRoute
  '/staff-portal/teachers': typeof StaffPortalTeachersRoute
  '/teacher-portal/attendance': typeof TeacherPortalAttendanceRoute
  '/teacher-portal/calendar': typeof TeacherPortalCalendarRoute
  '/teacher-portal/classes': typeof TeacherPortalClassesRoute
  '/teacher-portal/homework': typeof TeacherPortalHomeworkRoute
  '/teacher-portal/my-attendance': typeof TeacherPortalMyAttendanceRoute
  '/teacher-portal/notices': typeof TeacherPortalNoticesRoute
  '/teacher-portal/planner': typeof TeacherPortalPlannerRoute
  '/teacher-portal/profile': typeof TeacherPortalProfileRoute
  '/teacher-portal/pupa': typeof TeacherPortalPupaRoute
  '/teacher-portal/regularization': typeof TeacherPortalRegularizationRoute
  '/teacher-portal/students': typeof TeacherPortalStudentsRoute
  '/staff-portal/': typeof StaffPortalIndexRoute
  '/teacher-portal/': typeof TeacherPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRoute
  '/teacher': typeof TeacherRoute
  '/academics': typeof PortalAcademicsRoute
  '/attendance': typeof PortalAttendanceRoute
  '/bus': typeof PortalBusRoute
  '/cafeteria': typeof PortalCafeteriaRoute
  '/calendar': typeof PortalCalendarRoute
  '/dashboard': typeof PortalDashboardRoute
  '/diary': typeof PortalDiaryRoute
  '/documents': typeof PortalDocumentsRoute
  '/fees': typeof PortalFeesRoute
  '/gallery': typeof PortalGalleryRoute
  '/homework': typeof PortalHomeworkRoute
  '/noticeboard': typeof PortalNoticeboardRoute
  '/profile': typeof PortalProfileRoute
  '/report-cards': typeof PortalReportCardsRoute
  '/settings': typeof PortalSettingsRoute
  '/staff-portal/attendance': typeof StaffPortalAttendanceRoute
  '/staff-portal/classes': typeof StaffPortalClassesRoute
  '/staff-portal/homework': typeof StaffPortalHomeworkRoute
  '/staff-portal/notices': typeof StaffPortalNoticesRoute
  '/staff-portal/profile': typeof StaffPortalProfileRoute
  '/staff-portal/regularization': typeof StaffPortalRegularizationRoute
  '/staff-portal/students': typeof StaffPortalStudentsRoute
  '/staff-portal/teacher-attendance': typeof StaffPortalTeacherAttendanceRoute
  '/staff-portal/teachers': typeof StaffPortalTeachersRoute
  '/teacher-portal/attendance': typeof TeacherPortalAttendanceRoute
  '/teacher-portal/calendar': typeof TeacherPortalCalendarRoute
  '/teacher-portal/classes': typeof TeacherPortalClassesRoute
  '/teacher-portal/homework': typeof TeacherPortalHomeworkRoute
  '/teacher-portal/my-attendance': typeof TeacherPortalMyAttendanceRoute
  '/teacher-portal/notices': typeof TeacherPortalNoticesRoute
  '/teacher-portal/planner': typeof TeacherPortalPlannerRoute
  '/teacher-portal/profile': typeof TeacherPortalProfileRoute
  '/teacher-portal/pupa': typeof TeacherPortalPupaRoute
  '/teacher-portal/regularization': typeof TeacherPortalRegularizationRoute
  '/teacher-portal/students': typeof TeacherPortalStudentsRoute
  '/staff-portal': typeof StaffPortalIndexRoute
  '/teacher-portal': typeof TeacherPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRoute
  '/staff-portal': typeof StaffPortalRouteWithChildren
  '/teacher': typeof TeacherRoute
  '/teacher-portal': typeof TeacherPortalRouteWithChildren
  '/_portal/academics': typeof PortalAcademicsRoute
  '/_portal/attendance': typeof PortalAttendanceRoute
  '/_portal/bus': typeof PortalBusRoute
  '/_portal/cafeteria': typeof PortalCafeteriaRoute
  '/_portal/calendar': typeof PortalCalendarRoute
  '/_portal/dashboard': typeof PortalDashboardRoute
  '/_portal/diary': typeof PortalDiaryRoute
  '/_portal/documents': typeof PortalDocumentsRoute
  '/_portal/fees': typeof PortalFeesRoute
  '/_portal/gallery': typeof PortalGalleryRoute
  '/_portal/homework': typeof PortalHomeworkRoute
  '/_portal/noticeboard': typeof PortalNoticeboardRoute
  '/_portal/profile': typeof PortalProfileRoute
  '/_portal/report-cards': typeof PortalReportCardsRoute
  '/_portal/settings': typeof PortalSettingsRoute
  '/staff-portal/attendance': typeof StaffPortalAttendanceRoute
  '/staff-portal/classes': typeof StaffPortalClassesRoute
  '/staff-portal/homework': typeof StaffPortalHomeworkRoute
  '/staff-portal/notices': typeof StaffPortalNoticesRoute
  '/staff-portal/profile': typeof StaffPortalProfileRoute
  '/staff-portal/regularization': typeof StaffPortalRegularizationRoute
  '/staff-portal/students': typeof StaffPortalStudentsRoute
  '/staff-portal/teacher-attendance': typeof StaffPortalTeacherAttendanceRoute
  '/staff-portal/teachers': typeof StaffPortalTeachersRoute
  '/teacher-portal/attendance': typeof TeacherPortalAttendanceRoute
  '/teacher-portal/calendar': typeof TeacherPortalCalendarRoute
  '/teacher-portal/classes': typeof TeacherPortalClassesRoute
  '/teacher-portal/homework': typeof TeacherPortalHomeworkRoute
  '/teacher-portal/my-attendance': typeof TeacherPortalMyAttendanceRoute
  '/teacher-portal/notices': typeof TeacherPortalNoticesRoute
  '/teacher-portal/planner': typeof TeacherPortalPlannerRoute
  '/teacher-portal/profile': typeof TeacherPortalProfileRoute
  '/teacher-portal/pupa': typeof TeacherPortalPupaRoute
  '/teacher-portal/regularization': typeof TeacherPortalRegularizationRoute
  '/teacher-portal/students': typeof TeacherPortalStudentsRoute
  '/staff-portal/': typeof StaffPortalIndexRoute
  '/teacher-portal/': typeof TeacherPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/staff'
    | '/staff-portal'
    | '/teacher'
    | '/teacher-portal'
    | '/academics'
    | '/attendance'
    | '/bus'
    | '/cafeteria'
    | '/calendar'
    | '/dashboard'
    | '/diary'
    | '/documents'
    | '/fees'
    | '/gallery'
    | '/homework'
    | '/noticeboard'
    | '/profile'
    | '/report-cards'
    | '/settings'
    | '/staff-portal/attendance'
    | '/staff-portal/classes'
    | '/staff-portal/homework'
    | '/staff-portal/notices'
    | '/staff-portal/profile'
    | '/staff-portal/regularization'
    | '/staff-portal/students'
    | '/staff-portal/teacher-attendance'
    | '/staff-portal/teachers'
    | '/teacher-portal/attendance'
    | '/teacher-portal/calendar'
    | '/teacher-portal/classes'
    | '/teacher-portal/homework'
    | '/teacher-portal/my-attendance'
    | '/teacher-portal/notices'
    | '/teacher-portal/planner'
    | '/teacher-portal/profile'
    | '/teacher-portal/pupa'
    | '/teacher-portal/regularization'
    | '/teacher-portal/students'
    | '/staff-portal/'
    | '/teacher-portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/staff'
    | '/teacher'
    | '/academics'
    | '/attendance'
    | '/bus'
    | '/cafeteria'
    | '/calendar'
    | '/dashboard'
    | '/diary'
    | '/documents'
    | '/fees'
    | '/gallery'
    | '/homework'
    | '/noticeboard'
    | '/profile'
    | '/report-cards'
    | '/settings'
    | '/staff-portal/attendance'
    | '/staff-portal/classes'
    | '/staff-portal/homework'
    | '/staff-portal/notices'
    | '/staff-portal/profile'
    | '/staff-portal/regularization'
    | '/staff-portal/students'
    | '/staff-portal/teacher-attendance'
    | '/staff-portal/teachers'
    | '/teacher-portal/attendance'
    | '/teacher-portal/calendar'
    | '/teacher-portal/classes'
    | '/teacher-portal/homework'
    | '/teacher-portal/my-attendance'
    | '/teacher-portal/notices'
    | '/teacher-portal/planner'
    | '/teacher-portal/profile'
    | '/teacher-portal/pupa'
    | '/teacher-portal/regularization'
    | '/teacher-portal/students'
    | '/staff-portal'
    | '/teacher-portal'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/auth'
    | '/staff'
    | '/staff-portal'
    | '/teacher'
    | '/teacher-portal'
    | '/_portal/academics'
    | '/_portal/attendance'
    | '/_portal/bus'
    | '/_portal/cafeteria'
    | '/_portal/calendar'
    | '/_portal/dashboard'
    | '/_portal/diary'
    | '/_portal/documents'
    | '/_portal/fees'
    | '/_portal/gallery'
    | '/_portal/homework'
    | '/_portal/noticeboard'
    | '/_portal/profile'
    | '/_portal/report-cards'
    | '/_portal/settings'
    | '/staff-portal/attendance'
    | '/staff-portal/classes'
    | '/staff-portal/homework'
    | '/staff-portal/notices'
    | '/staff-portal/profile'
    | '/staff-portal/regularization'
    | '/staff-portal/students'
    | '/staff-portal/teacher-attendance'
    | '/staff-portal/teachers'
    | '/teacher-portal/attendance'
    | '/teacher-portal/calendar'
    | '/teacher-portal/classes'
    | '/teacher-portal/homework'
    | '/teacher-portal/my-attendance'
    | '/teacher-portal/notices'
    | '/teacher-portal/planner'
    | '/teacher-portal/profile'
    | '/teacher-portal/pupa'
    | '/teacher-portal/regularization'
    | '/teacher-portal/students'
    | '/staff-portal/'
    | '/teacher-portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  AuthRoute: typeof AuthRoute
  StaffRoute: typeof StaffRoute
  StaffPortalRoute: typeof StaffPortalRouteWithChildren
  TeacherRoute: typeof TeacherRoute
  TeacherPortalRoute: typeof TeacherPortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher-portal': {
      id: '/teacher-portal'
      path: '/teacher-portal'
      fullPath: '/teacher-portal'
      preLoaderRoute: typeof TeacherPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-portal': {
      id: '/staff-portal'
      path: '/staff-portal'
      fullPath: '/staff-portal'
      preLoaderRoute: typeof StaffPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-portal/': {
      id: '/teacher-portal/'
      path: '/'
      fullPath: '/teacher-portal/'
      preLoaderRoute: typeof TeacherPortalIndexRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/staff-portal/': {
      id: '/staff-portal/'
      path: '/'
      fullPath: '/staff-portal/'
      preLoaderRoute: typeof StaffPortalIndexRouteImport
      parentRoute: typeof StaffPortalRoute
    }
    '/teacher-portal/students': {
      id: '/teacher-portal/students'
      path: '/students'
      fullPath: '/teacher-portal/students'
      preLoaderRoute: typeof TeacherPortalStudentsRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/teacher-portal/regularization': {
      id: '/teacher-portal/regularization'
      path: '/regularization'
      fullPath: '/teacher-portal/regularization'
      preLoaderRoute: typeof TeacherPortalRegularizationRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/teacher-portal/pupa': {
      id: '/teacher-portal/pupa'
      path: '/pupa'
      fullPath: '/teacher-portal/pupa'
      preLoaderRoute: typeof TeacherPortalPupaRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/teacher-portal/profile': {
      id: '/teacher-portal/profile'
      path: '/profile'
      fullPath: '/teacher-portal/profile'
      preLoaderRoute: typeof TeacherPortalProfileRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/teacher-portal/planner': {
      id: '/teacher-portal/planner'
      path: '/planner'
      fullPath: '/teacher-portal/planner'
      preLoaderRoute: typeof TeacherPortalPlannerRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/teacher-portal/notices': {
      id: '/teacher-portal/notices'
      path: '/notices'
      fullPath: '/teacher-portal/notices'
      preLoaderRoute: typeof TeacherPortalNoticesRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/teacher-portal/my-attendance': {
      id: '/teacher-portal/my-attendance'
      path: '/my-attendance'
      fullPath: '/teacher-portal/my-attendance'
      preLoaderRoute: typeof TeacherPortalMyAttendanceRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/teacher-portal/homework': {
      id: '/teacher-portal/homework'
      path: '/homework'
      fullPath: '/teacher-portal/homework'
      preLoaderRoute: typeof TeacherPortalHomeworkRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/teacher-portal/classes': {
      id: '/teacher-portal/classes'
      path: '/classes'
      fullPath: '/teacher-portal/classes'
      preLoaderRoute: typeof TeacherPortalClassesRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/teacher-portal/calendar': {
      id: '/teacher-portal/calendar'
      path: '/calendar'
      fullPath: '/teacher-portal/calendar'
      preLoaderRoute: typeof TeacherPortalCalendarRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/teacher-portal/attendance': {
      id: '/teacher-portal/attendance'
      path: '/attendance'
      fullPath: '/teacher-portal/attendance'
      preLoaderRoute: typeof TeacherPortalAttendanceRouteImport
      parentRoute: typeof TeacherPortalRoute
    }
    '/staff-portal/teachers': {
      id: '/staff-portal/teachers'
      path: '/teachers'
      fullPath: '/staff-portal/teachers'
      preLoaderRoute: typeof StaffPortalTeachersRouteImport
      parentRoute: typeof StaffPortalRoute
    }
    '/staff-portal/teacher-attendance': {
      id: '/staff-portal/teacher-attendance'
      path: '/teacher-attendance'
      fullPath: '/staff-portal/teacher-attendance'
      preLoaderRoute: typeof StaffPortalTeacherAttendanceRouteImport
      parentRoute: typeof StaffPortalRoute
    }
    '/staff-portal/students': {
      id: '/staff-portal/students'
      path: '/students'
      fullPath: '/staff-portal/students'
      preLoaderRoute: typeof StaffPortalStudentsRouteImport
      parentRoute: typeof StaffPortalRoute
    }
    '/staff-portal/regularization': {
      id: '/staff-portal/regularization'
      path: '/regularization'
      fullPath: '/staff-portal/regularization'
      preLoaderRoute: typeof StaffPortalRegularizationRouteImport
      parentRoute: typeof StaffPortalRoute
    }
    '/staff-portal/profile': {
      id: '/staff-portal/profile'
      path: '/profile'
      fullPath: '/staff-portal/profile'
      preLoaderRoute: typeof StaffPortalProfileRouteImport
      parentRoute: typeof StaffPortalRoute
    }
    '/staff-portal/notices': {
      id: '/staff-portal/notices'
      path: '/notices'
      fullPath: '/staff-portal/notices'
      preLoaderRoute: typeof StaffPortalNoticesRouteImport
      parentRoute: typeof StaffPortalRoute
    }
    '/staff-portal/homework': {
      id: '/staff-portal/homework'
      path: '/homework'
      fullPath: '/staff-portal/homework'
      preLoaderRoute: typeof StaffPortalHomeworkRouteImport
      parentRoute: typeof StaffPortalRoute
    }
    '/staff-portal/classes': {
      id: '/staff-portal/classes'
      path: '/classes'
      fullPath: '/staff-portal/classes'
      preLoaderRoute: typeof StaffPortalClassesRouteImport
      parentRoute: typeof StaffPortalRoute
    }
    '/staff-portal/attendance': {
      id: '/staff-portal/attendance'
      path: '/attendance'
      fullPath: '/staff-portal/attendance'
      preLoaderRoute: typeof StaffPortalAttendanceRouteImport
      parentRoute: typeof StaffPortalRoute
    }
    '/_portal/settings': {
      id: '/_portal/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/report-cards': {
      id: '/_portal/report-cards'
      path: '/report-cards'
      fullPath: '/report-cards'
      preLoaderRoute: typeof PortalReportCardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/profile': {
      id: '/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/noticeboard': {
      id: '/_portal/noticeboard'
      path: '/noticeboard'
      fullPath: '/noticeboard'
      preLoaderRoute: typeof PortalNoticeboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/homework': {
      id: '/_portal/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof PortalHomeworkRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/gallery': {
      id: '/_portal/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PortalGalleryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/fees': {
      id: '/_portal/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof PortalFeesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/documents': {
      id: '/_portal/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/diary': {
      id: '/_portal/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof PortalDiaryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/dashboard': {
      id: '/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/calendar': {
      id: '/_portal/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof PortalCalendarRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/cafeteria': {
      id: '/_portal/cafeteria'
      path: '/cafeteria'
      fullPath: '/cafeteria'
      preLoaderRoute: typeof PortalCafeteriaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/bus': {
      id: '/_portal/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof PortalBusRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/attendance': {
      id: '/_portal/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof PortalAttendanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/academics': {
      id: '/_portal/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof PortalAcademicsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAcademicsRoute: typeof PortalAcademicsRoute
  PortalAttendanceRoute: typeof PortalAttendanceRoute
  PortalBusRoute: typeof PortalBusRoute
  PortalCafeteriaRoute: typeof PortalCafeteriaRoute
  PortalCalendarRoute: typeof PortalCalendarRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalDiaryRoute: typeof PortalDiaryRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalFeesRoute: typeof PortalFeesRoute
  PortalGalleryRoute: typeof PortalGalleryRoute
  PortalHomeworkRoute: typeof PortalHomeworkRoute
  PortalNoticeboardRoute: typeof PortalNoticeboardRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalReportCardsRoute: typeof PortalReportCardsRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAcademicsRoute: PortalAcademicsRoute,
  PortalAttendanceRoute: PortalAttendanceRoute,
  PortalBusRoute: PortalBusRoute,
  PortalCafeteriaRoute: PortalCafeteriaRoute,
  PortalCalendarRoute: PortalCalendarRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalDiaryRoute: PortalDiaryRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalFeesRoute: PortalFeesRoute,
  PortalGalleryRoute: PortalGalleryRoute,
  PortalHomeworkRoute: PortalHomeworkRoute,
  PortalNoticeboardRoute: PortalNoticeboardRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalReportCardsRoute: PortalReportCardsRoute,
  PortalSettingsRoute: PortalSettingsRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface StaffPortalRouteChildren {
  StaffPortalAttendanceRoute: typeof StaffPortalAttendanceRoute
  StaffPortalClassesRoute: typeof StaffPortalClassesRoute
  StaffPortalHomeworkRoute: typeof StaffPortalHomeworkRoute
  StaffPortalNoticesRoute: typeof StaffPortalNoticesRoute
  StaffPortalProfileRoute: typeof StaffPortalProfileRoute
  StaffPortalRegularizationRoute: typeof StaffPortalRegularizationRoute
  StaffPortalStudentsRoute: typeof StaffPortalStudentsRoute
  StaffPortalTeacherAttendanceRoute: typeof StaffPortalTeacherAttendanceRoute
  StaffPortalTeachersRoute: typeof StaffPortalTeachersRoute
  StaffPortalIndexRoute: typeof StaffPortalIndexRoute
}

const StaffPortalRouteChildren: StaffPortalRouteChildren = {
  StaffPortalAttendanceRoute: StaffPortalAttendanceRoute,
  StaffPortalClassesRoute: StaffPortalClassesRoute,
  StaffPortalHomeworkRoute: StaffPortalHomeworkRoute,
  StaffPortalNoticesRoute: StaffPortalNoticesRoute,
  StaffPortalProfileRoute: StaffPortalProfileRoute,
  StaffPortalRegularizationRoute: StaffPortalRegularizationRoute,
  StaffPortalStudentsRoute: StaffPortalStudentsRoute,
  StaffPortalTeacherAttendanceRoute: StaffPortalTeacherAttendanceRoute,
  StaffPortalTeachersRoute: StaffPortalTeachersRoute,
  StaffPortalIndexRoute: StaffPortalIndexRoute,
}

const StaffPortalRouteWithChildren = StaffPortalRoute._addFileChildren(
  StaffPortalRouteChildren,
)

interface TeacherPortalRouteChildren {
  TeacherPortalAttendanceRoute: typeof TeacherPortalAttendanceRoute
  TeacherPortalCalendarRoute: typeof TeacherPortalCalendarRoute
  TeacherPortalClassesRoute: typeof TeacherPortalClassesRoute
  TeacherPortalHomeworkRoute: typeof TeacherPortalHomeworkRoute
  TeacherPortalMyAttendanceRoute: typeof TeacherPortalMyAttendanceRoute
  TeacherPortalNoticesRoute: typeof TeacherPortalNoticesRoute
  TeacherPortalPlannerRoute: typeof TeacherPortalPlannerRoute
  TeacherPortalProfileRoute: typeof TeacherPortalProfileRoute
  TeacherPortalPupaRoute: typeof TeacherPortalPupaRoute
  TeacherPortalRegularizationRoute: typeof TeacherPortalRegularizationRoute
  TeacherPortalStudentsRoute: typeof TeacherPortalStudentsRoute
  TeacherPortalIndexRoute: typeof TeacherPortalIndexRoute
}

const TeacherPortalRouteChildren: TeacherPortalRouteChildren = {
  TeacherPortalAttendanceRoute: TeacherPortalAttendanceRoute,
  TeacherPortalCalendarRoute: TeacherPortalCalendarRoute,
  TeacherPortalClassesRoute: TeacherPortalClassesRoute,
  TeacherPortalHomeworkRoute: TeacherPortalHomeworkRoute,
  TeacherPortalMyAttendanceRoute: TeacherPortalMyAttendanceRoute,
  TeacherPortalNoticesRoute: TeacherPortalNoticesRoute,
  TeacherPortalPlannerRoute: TeacherPortalPlannerRoute,
  TeacherPortalProfileRoute: TeacherPortalProfileRoute,
  TeacherPortalPupaRoute: TeacherPortalPupaRoute,
  TeacherPortalRegularizationRoute: TeacherPortalRegularizationRoute,
  TeacherPortalStudentsRoute: TeacherPortalStudentsRoute,
  TeacherPortalIndexRoute: TeacherPortalIndexRoute,
}

const TeacherPortalRouteWithChildren = TeacherPortalRoute._addFileChildren(
  TeacherPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  AuthRoute: AuthRoute,
  StaffRoute: StaffRoute,
  StaffPortalRoute: StaffPortalRouteWithChildren,
  TeacherRoute: TeacherRoute,
  TeacherPortalRoute: TeacherPortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
